version: '3.9'

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - ENSHawk
    volumes:
       - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
      container_name: kb-container
      image: docker.elastic.co/kibana/kibana:8.6.0
      restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://es-container:9200
      networks:
        - ENSHawk
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601


volumes:
  es_data:
    driver: local

networks:
  ENSHawk:
    driver: bridge

# networks:
#   default:
#     external:
#       name: ENSHawk