"""added column hash to domains table

Revision ID: c71705657f4d
Revises: f5cf853769be
Create Date: 2022-09-26 14:58:21.537662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71705657f4d'
down_revision = 'f5cf853769be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('hash', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'hash')
    # ### end Alembic commands ###
