"""adding listing and bids details

Revision ID: f5cf853769be
Revises: 
Create Date: 2022-09-14 08:21:57.672622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cf853769be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('bids_details', sa.String(length=300), nullable=True))
    op.add_column('domains', sa.Column('listings_details', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'listings_details')
    op.drop_column('domains', 'bids_details')
    # ### end Alembic commands ###
